@startuml

title __SRC's Class Diagram__\n

  namespace  {
    class Broccoli {
        ~ Broccoli()
        ~ cost()
        ~ getDescription()
    }
  }
  

  namespace  {
    class Cheese {
        ~ Cheese()
        ~ cost()
        ~ getDescription()
    }
  }
  

  namespace  {
    class Chicken {
        ~ Chicken()
        ~ cost()
        ~ getDescription()
    }
  }
  

  namespace  {
    abstract class Decorator {
        {abstract} ~ getDescription()
    }
  }
  

  namespace  {
    class Ham {
        ~ Ham()
        ~ cost()
        ~ getDescription()
    }
  }
  

  namespace  {
    class MeatHeaven {
        ~ MeatHeaven()
        ~ cost()
    }
  }
  

  namespace  {
    abstract class Pizza {
        ~ description : String
        {abstract} ~ cost()
        ~ getDescription()
    }
  }
  

  namespace  {
    class Spinach {
        ~ Spinach()
        ~ cost()
        ~ getDescription()
    }
  }
  

  namespace  {
    class TestDrive {
        {static} + main()
        {static} - formatSum()
    }
  }
  

  namespace  {
    class Tomato {
        ~ Tomato()
        ~ cost()
        ~ getDescription()
    }
  }
  

  namespace  {
    class Vegan {
        ~ Vegan()
        ~ cost()
    }
  }
  

  Broccoli -up-|> Decorator
  Broccoli o-- Pizza : pizza
  Cheese -up-|> Decorator
  Cheese o-- Pizza : pizza
  Chicken -up-|> Decorator
  Chicken o-- Pizza : pizza
  Decorator -up-|> Pizza
  Ham -up-|> Decorator
  Ham o-- Pizza : pizza
  MeatHeaven -up-|> Pizza
  Spinach -up-|> Decorator
  Spinach o-- Pizza : pizza
  Tomato -up-|> Decorator
  Tomato o-- Pizza : pizza
  Vegan -up-|> Pizza


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
